version: '2'
services:
  fastlogger:
    image: garci66/fastzabbixlogger
    restart: always
    volumes:
     - ./speed-log.txt:/speed-log.txt
    environment:
     - TZ=America/Argentina/Buenos_Aires
